# Title     : Soil Numbers To Letters
# Objective : Converts numbers generated by the soil rating class into their appropriate letters
# Created by: Thomas Curtis
# Created on: 2020-03-09

soilNumbersToLetters <- function(number){
  #TODO: convert number to letters
  return(number)
}