# Title     : Soil Numbers To Letters
# Objective : Converts numbers generated by the soil rating class into their appropriate letters
# Created by: Thomas Curtis
# Created on: 2020-03-09

soilNumbersToLetters <- function(number){
  soilRating <- floor(number/1000000)
  soilRating[(floor(number%%1000000/100000)==1)] <- paste0(soilRating[(floor(number%%1000000/100000)==1)],"M")
  soilRating[(floor(number%%1000000/100000)==2)] <- paste0(soilRating[(floor(number%%1000000/100000)==2)],"A")
  soilRating[(floor(number%%100000/10000)==1)] <- paste0(soilRating[(floor(number%%100000/10000)==1)],"D")
  soilRating[(floor(number%%10000/1000)==1)] <- paste0(soilRating[(floor(number%%10000/1000)==1)],"F")
  soilRating[(floor(number%%1000/100)==1)] <- paste0(soilRating[(floor(number%%1000/100)==1)],"V")
  soilRating[(floor(number%%100/10)==1)] <- paste0(soilRating[(floor(number%%100/10)==1)],"N")
  soilRating[(floor(number%%10)==1)] <- paste0(soilRating[(floor(number%%10)==1)],"Y")
  return(soilRating)
}